### ISSUE TITLE
Batch failure: ContainerInvalidSettings

### ISSUE THREAD

**Issue by marcelvb** [Azure/Batch#4]
I have started using the container features of Azure Batch using the Azure Batch .NET SDK (Azure.Batch 8.1.2). I notice that every first task that runs on a node fails with the following error:

```
  "executionInfo": {
    "startTime": "2018-07-05T09:13:05.244Z",
    "endTime": "2018-07-05T09:24:25.698Z",
    "failureInfo": {
      "category": "UserError",
      "code": "ContainerInvalidSettings",
      "message": "At least one value of specified task container settings is invalid",
      "details": [
        {
          "name": "Message",
          "value": "UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)"
        }
      ]
    },
    "retryCount": 0,
    "requeueCount": 0,
    "result": "Failure"
  },
```

The following tasks of that same job on the same node usually work.

My pool is created as follows:
```
      // Specify a container registry
      ContainerRegistry containerRegistry = new ContainerRegistry(
          registryServer: Settings.DockerRegistry,
          userName: Settings.DockerRegistryUsername,
          password: Settings.DockerRegistryPassword);

      // Create container configuration, prefetching Docker images from the container registry
      var dockerImage = $"{Settings.DockerRegistry}/{Settings.DockerImage}";
      ContainerConfiguration containerConfig = new ContainerConfiguration
      {
        ContainerImageNames = new List<string> { dockerImage },
        ContainerRegistries = new List<ContainerRegistry> { containerRegistry }
      };

      ImageReference imageReference = new ImageReference(
        publisher: "microsoft-azure-batch",
        offer: "ubuntu-server-container",
        sku: "16-04-lts",
        version: "latest");

      // VM configuration
      string nodeAgentSkuId = "batch.node.ubuntu 16.04";
      VirtualMachineConfiguration virtualMachineConfiguration = new VirtualMachineConfiguration(imageReference, nodeAgentSkuId)
      {
        ContainerConfiguration = containerConfig
      };
    
      // Create the unbound pool object using the VirtualMachineConfiguration
      // created above
      CloudPool pool = batchClient.PoolOperations.CreatePool(
        poolId: poolId,
        virtualMachineSize: Settings.VmSize,
        virtualMachineConfiguration: virtualMachineConfiguration
      );

      pool.MaxTasksPerComputeNode = Settings.MaxTasksPerComputeNode;
      pool.TaskSchedulingPolicy = new TaskSchedulingPolicy(ComputeNodeFillType.Pack);
      pool.AutoScaleEnabled = true;
      pool.AutoScaleFormula = "$TargetDedicated = 0"; // create pool with zero nodes (scale later)

      // Commit the pool to the Batch service
      pool.Commit();
```

The registry is a Azure Container Registry (SKU: standard). All resources are in the same subscription and region (West Europe).

Before the SDK supported containers, I had a job start task that pulled the image from the Docker registry and the actual task would do a docker run. This was working fine, but I was afraid this might not be efficient or optimized, so I choose to use Azure Batch's container features.

**Comment by marcelvb** [comment]
Also, it seems that nodes that fail stay idle forever and don't process any jobs, while we do get billed for them.

**Comment by alfpark** [comment]
Please post your task commandline (redact anything sensitive).

Also, if you don't specify `--rm`, you can SSH into the node and run `docker inspect` on the container to get some more details (if the container was created).

**Comment by marcelvb** [comment]
For the job preparation task it looks like this (preparation task just pulls in files from blob storage and calls this just to test it's working):
```
"commandLine": "/bin/bash -c 'set -e; set -o pipefail; ls -l;python /imageprocessing/client.py --version; wait'"
```

For the actual task it looks like this:
```
"commandLine": "/bin/bash -c 'set -e; set -o pipefail; python /imageprocessing/client.py --no-multiprocessing --io batch run -s $AZ_BATCH_JOB_PREP_WORKING_DIR -i $AZ_BATCH_TASK_WORKING_DIR 2824cf01-c1f3-4dec-a5a7-5e790a6f8cfe.xml 6ca0c436-c903-496c-bf65-4ce6b875ac0e.xml bb21c1c9-e768-43d8-acb5-5a2ba83439ae.xml f810042e-dcfe-4b53-afa2-d99776a78fce.xml 8803555f-e45d-45ff-b2b2-3fd97813e199.xml 267b96e6-aa8f-4894-a203-39733c2345ff.xml be8a2ffd-2d2e-4449-8774-f0da80d541ae.xml 09757166-fff7-45ac-aa10-726add2e3689.xml 2a848d47-5df3-429a-89a0-97e0a1b90666.xml f3361b3d-a9e8-4acb-9394-1d3320d166b5.xml; wait'",
```

I undid all my Azure Batch SDK Container stuff and replaced it with the code I had before (calling docker pull in the preparation task and calling docker run in the actual tasks) and this again works fine.

So I'm wondering what is the invalid container setting Azure Batch is complaining about and where does `UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)` come from?

The node is gone, so I can't ssh into it anymore.

**Comment by marcelvb** [comment]
The error might come from the docker client maybe: #https://github.com/docker/docker-py/issues/398

**Comment by alfpark** [comment]
That is possible, thanks for pointing that out. Just to be sure, can you post your container settings (redacted)?

**Comment by marcelvb** [comment]
I'm not adding any run options if that is what you mean. The code for creating the task is this:

```
      AutoUserSpecification autoUserSpecification = new AutoUserSpecification(AutoUserScope.Pool, ElevationLevel.Admin);

      var xmlFileListString = string.Join(" ", xmlFileList);

      string rawDataStorageConnectionString = $"DefaultEndpointsProtocol=https;AccountName={Settings.RawDataStorageAccountName};AccountKey={Settings.RawDataStorageAccountAccessKey}";
      string imageStorageConnectionString = $"DefaultEndpointsProtocol=https;AccountName={Settings.ImageStorageAccountName};AccountKey={Settings.ImageStorageAccountAccessKey}";

      var dockerImage = $"{Settings.DockerRegistry}/{Settings.DockerImage}";

      ContainerRegistry containerRegistry = new ContainerRegistry(
        registryServer: Settings.DockerRegistry,
        userName: Settings.DockerRegistryUsername,
        password: Settings.DockerRegistryPassword);

      TaskContainerSettings cmdContainerSettings = new TaskContainerSettings(
          imageName: dockerImage, 
          registry: containerRegistry
// no containerRunOptions
      );

      EnvironmentSetting[] envSettings = {
        new EnvironmentSetting("STORAGECONNECTIONSTRING", rawDataStorageConnectionString),
        new EnvironmentSetting("IMG_STORAGECONNECTIONSTRING", imageStorageConnectionString),
      };

      string[] taskCommands = { $"python /imageprocessing/client.py --no-multiprocessing --io batch run -s $AZ_BATCH_JOB_PREP_WORKING_DIR -i $AZ_BATCH_TASK_WORKING_DIR {xmlFileListString}" };

      List<OutputFile> outputFiles = GetTaskOutputFiles(jobId, taskId);

      CloudTask task = new CloudTask($"{taskId}", WrapCommands(taskCommands))
      {
        UserIdentity = new UserIdentity(autoUserSpecification),
        EnvironmentSettings = envSettings,
        ResourceFiles = taskResourcefiles,
        OutputFiles = outputFiles,
        Constraints = new TaskConstraints { MaxTaskRetryCount = 2, MaxWallClockTime = TimeSpan.FromHours(1) },
        ContainerSettings = cmdContainerSettings
      };

      IList<CloudTask> tasks = new List<CloudTask>(new[] { task });
      batchClient.JobOperations.AddTask(jobId, tasks);
```

**Comment by alfpark** [comment]
Thanks, this is helpful. We'll investigate further.

**Comment by alfpark** [comment]
This bug was fixed in 1.3.0.8.

**Comment by marcelvb** [comment]
Looks like I still have this problem. I now included the ContainerSetting "--rm", but I don't think it's related. Most of my nodes are now idle while there are many tasks active. One task succeeded.

Result json:
[job-901098d2-eedc-44e1-b604-fab1cf7f1a3f-201808241533-r.imgproc-00001.json.txt](https://github.com/Azure/Batch/files/2319164/job-901098d2-eedc-44e1-b604-fab1cf7f1a3f-201808241533-r.imgproc-00001.json.txt)

I deleted my old pool and created a new one, so I guess I should have fresh nodes and recent node agent.

**Comment by xingwu1** [comment]
@marcelvb Do you still see the exactly UnixHTTPConnectionPool time out error?

**Comment by xingwu1** [comment]
@marcelvb We couldn't repro this bug in house, so the original bug fix miss catching the requests Timeout exception. We will roll out another fix ASAP.

**Comment by marcelvb** [comment]
Yes, I see this one: `UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)`

**Comment by marcelvb** [comment]
Looks like I still have this problem. I now included the ContainerSetting "--rm", but I don't think it's related. Most of my nodes are now idle while there are many tasks active. One task succeeded.

Result json:
[job-901098d2-eedc-44e1-b604-fab1cf7f1a3f-201808241533-r.imgproc-00001.json.txt](https://github.com/Azure/Batch/files/2319164/job-901098d2-eedc-44e1-b604-fab1cf7f1a3f-201808241533-r.imgproc-00001.json.txt)

I deleted my old pool and created a new one, so I guess I should have fresh nodes and recent node agent.

**Comment by marcelvb** [comment]
I see that some tasks have failed preparation task. The result is the task stays active, but doesn't do anything. The nodes stay up but are idle. This means we are paying for something doesn't do anything. It seems to fail also when there is only one tasks, so it does not seem to be related to high load (unless it's unrelated load on the container registery).

We would like to go into production with this solution soon, but we can't. Please let me know if I can provide you with any information to reproduce this problem.

**Comment by SDubrulle** [comment]
I'm still bumping into this issue. Any idea on how to solve this?

**Comment by uandrei** [comment]
Hi, so this issue seems to be popping up quite randomly and when it does it makes the batch account unusable for a period of time.

Do you have any root cause of why this is happening?

**Comment by cantpitch** [comment]
We are still experiencing this issue. It seems to happen randomly, but regularly. There doesn't seem to be a way to specify a longer timeout than 60 seconds anywhere which would likely resolve the issue for us.

Often, running the exact same job immediately after will work fine.

`UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)`

**Comment by michaelcredera** [comment]
I also experience this error with some regularity in my batch deployment - same exact symptoms.

Seems related to this error:

https://github.com/docker/docker-py/issues/398

But the SDK doesn't expose a way to change node environment variables (as far as I know), so I'm not sure how to address this.

**Comment by chrisgavin** [comment]
I was getting this error a lot on an Azure batch task, and the problem was that I was using a very big container image. This image takes more than 60 seconds to create a container from, hence the create call was timing out.

It would be nice if there were a better fix for this (e.g. the ability to customize the Docker socket read timeout), but for me I just solved it by trying to cut down my image size as much as possible to make it faster to make a container from.

**Comment by staer** [comment]
How big is "very big"? Curious from a reproduction standpoint

**Comment by cantpitch** [comment]
10GB made it happen pretty regularly for me

**Comment by pditommaso** [comment]
Hello people, we are also observing this problem when pulling a container from Quay. 

It must be said it's not that big, just 2.5GB, however, it seems to happen when there is a contention accessing such a container ie. multiple tasks pulling it at the same time. Linking the discussion [here](https://github.com/nextflow-io/nextflow/discussions/2510).

Any suggesting to mitigate the problem?

**Comment by ossonts** [comment]
I am hitting this issue, usually when a node starts

I have 15 x standard_hb120rs_v2 and fill up a batch job queue. 

When the nodes come online (first boot) there are enough tasks to fill each machine 120 tasks per node.

Very often at this initial stage I see the following error on (approx. 15 error tasks out of 1800tasks)


```
ContainerSettings: -v /etc/ssl/certs:/etc/ssl/certs:ro -v /etc/pki:/etc/pki:ro
Message: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
```


I suspect it is related to 120 tasks all starting at the same time and we are using docker images. 

A quick google says that extending timeout to 120 sec may help, but I have been unable to set it? For example:

```
export DOCKER_CLIENT_TIMEOUT=120
```
Ideas?

**Comment by alfpark** [comment]
Remediation has been applied in Node Agent version 1.11.3: https://github.com/Azure/Batch/blob/master/changelogs/nodeagent/CHANGELOG.md#1113
